### ISSUE TITLE
Upgrade: Fix overwriting of comments in config file.

### ISSUE THREAD

**Issue by rjulian** [cloudmitigator/reflex-cli#17]
Currently parser will strip out anything that's not valid yaml and we overwrite, whiping out all comments.

**Comment by MikeSchapp** [comment]
So I have reworked it so the upgrade command no longer removes comments. "Init" will still generate a fresh yaml file though.  Would love some feedback on it! @rjulian @mcbanderson 

Just need another set of eyes to ensure this makes sense!

**Comment by MikeSchapp** [comment]
Adding to the backlog, decided that ruamel.yaml seems to be a dependency risk at the moment, and PyYaml doesn't seem to have the comment support we want.

**Decisions**

- Continue with PyYAML
- Keep an eye out for the comment feature
- Investigate the possible use of PyYaml to create reflex.yaml instead of Jinja
